// ReSharper disable All

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace SteamLib.Core.Enums;

public enum Country
{
    Afghanistan,
    Aland_Islands,
    Albania,
    Algeria,
    American_Samoa,
    Andorra,
    Angola,
    Anguilla,
    Antigua_and_Barbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Bhutan,
    Bolivia,
    Bosnia_and_Herzegovina,
    Botswana,
    Brazil,
    Brunei_Darussalam,
    Bulgaria,
    Burundi,
    Cambodia,
    Cameroon,
    Canada,
    Cape_Verde,
    Cayman_Islands,
    Chad,
    Chile,
    China,
    Colombia,
    Congo,
    Costa_Rica,
    Cote_d_Ivoire,
    Croatia,
    Cyprus,
    Czech_Republic,
    Denmark,
    Dominica,
    Dominican_Republic,
    Ecuador,
    Egypt,
    El_Salvador,
    Estonia,
    Eswatini,
    Ethiopia,
    Faroe_Islands,
    Finland,
    France,
    French_Guiana,
    French_Polynesia,
    Gabon,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guernsey,
    Guyana,
    Haiti,
    Honduras,
    Hong_Kong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    Isle_of_Man,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jersey,
    Jordan,
    Kazakhstan,
    Kenya,
    Korea,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macau,
    Macedonia,
    Madagascar,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    Martinique,
    Mauritius,
    Mayotte,
    Mexico,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nepal,
    Netherlands,
    New_Zealand,
    Nicaragua,
    Nigeria,
    Northern_Mariana_Islands,
    Norway,
    Oman,
    Pakistan,
    Palestinian_Territory,
    Panama,
    Papua_New_Guinea,
    Paraguay,
    Peru,
    Philippines,
    Poland,
    Portugal,
    Puerto_Rico,
    Qatar,
    Reunion,
    Romania,
    Russian_Federation,
    Rwanda,
    Saint_Kitts_and_Nevis,
    Saint_Lucia,
    Saint_Vincent_and_the_Grenadines,
    Saudi_Arabia,
    Senegal,
    Serbia,
    Seychelles,
    Singapore,
    Slovakia,
    Slovenia,
    South_Africa,
    Spain,
    Sri_Lanka,
    Sudan,
    Suriname,
    Sweden,
    Switzerland,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    Togo,
    Trinidad_and_Tobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    Turks_and_Caicos_Islands,
    Uganda,
    Ukraine,
    United_Arab_Emirates,
    United_Kingdom,
    United_States,
    Uruguay,
    Uzbekistan,
    Venezuela,
    Viet_Nam,
    Virgin_Islands,
    Yemen,
    Zambia,
    Zimbabwe
}

public static class CountryResolver
{
    public static IReadOnlyDictionary<string, Country> ResolveByCountryCode = new ReadOnlyDictionary<string, Country>(
        new Dictionary<string, Country>()
        {
            {"US", Country.United_States},
            {"CA", Country.Canada},
            {"AF", Country.Afghanistan},
            {"AX", Country.Aland_Islands},
            {"AL", Country.Albania},
            {"DZ", Country.Algeria},
            {"AS", Country.American_Samoa},
            {"AD", Country.Andorra},
            {"AO", Country.Angola},
            {"AI", Country.Anguilla},
            {"AG", Country.Antigua_and_Barbuda},
            {"AR", Country.Argentina},
            {"AM", Country.Armenia},
            {"AW", Country.Aruba},
            {"AU", Country.Australia},
            {"AT", Country.Austria},
            {"AZ", Country.Azerbaijan},
            {"BS", Country.Bahamas},
            {"BH", Country.Bahrain},
            {"BD", Country.Bangladesh},
            {"BB", Country.Barbados},
            {"BY", Country.Belarus},
            {"BE", Country.Belgium},
            {"BZ", Country.Belize},
            {"BT", Country.Bhutan},
            {"BO", Country.Bolivia},
            {"BA", Country.Bosnia_and_Herzegovina},
            {"BW", Country.Botswana},
            {"BR", Country.Brazil},
            {"BN", Country.Brunei_Darussalam},
            {"BG", Country.Bulgaria},
            {"BI", Country.Burundi},
            {"KH", Country.Cambodia},
            {"CM", Country.Cameroon},
            {"CV", Country.Cape_Verde},
            {"KY", Country.Cayman_Islands},
            {"TD", Country.Chad},
            {"CL", Country.Chile},
            {"CN", Country.China},
            {"CO", Country.Colombia},
            {"CD", Country.Congo},
            {"CR", Country.Costa_Rica},
            {"CI", Country.Cote_d_Ivoire},
            {"HR", Country.Croatia},
            {"CY", Country.Cyprus},
            {"CZ", Country.Czech_Republic},
            {"DK", Country.Denmark},
            {"DM", Country.Dominica},
            {"DO", Country.Dominican_Republic},
            {"EC", Country.Ecuador},
            {"EG", Country.Egypt},
            {"SV", Country.El_Salvador},
            {"EE", Country.Estonia},
            {"ET", Country.Ethiopia},
            {"FO", Country.Faroe_Islands},
            {"FI", Country.Finland},
            {"FR", Country.France},
            {"GF", Country.French_Guiana},
            {"PF", Country.French_Polynesia},
            {"GA", Country.Gabon},
            {"GE", Country.Georgia},
            {"DE", Country.Germany},
            {"GH", Country.Ghana},
            {"GI", Country.Gibraltar},
            {"GR", Country.Greece},
            {"GL", Country.Greenland},
            {"GD", Country.Grenada},
            {"GP", Country.Guadeloupe},
            {"GU", Country.Guam},
            {"GT", Country.Guatemala},
            {"GG", Country.Guernsey},
            {"GY", Country.Guyana},
            {"HT", Country.Haiti},
            {"HN", Country.Honduras},
            {"HK", Country.Hong_Kong},
            {"HU", Country.Hungary},
            {"IS", Country.Iceland},
            {"IN", Country.India},
            {"ID", Country.Indonesia},
            {"IQ", Country.Iraq},
            {"IE", Country.Ireland},
            {"IR", Country.Iran},
            {"IM", Country.Isle_of_Man},
            {"IL", Country.Israel},
            {"IT", Country.Italy},
            {"JM", Country.Jamaica},
            {"JP", Country.Japan},
            {"JE", Country.Jersey},
            {"JO", Country.Jordan},
            {"KZ", Country.Kazakhstan},
            {"KE", Country.Kenya},
            {"KR", Country.Korea},
            {"KW", Country.Kuwait},
            {"KG", Country.Kyrgyzstan},
            {"LA", Country.Laos},
            {"LV", Country.Latvia},
            {"LB", Country.Lebanon},
            {"LY", Country.Libya},
            {"LI", Country.Liechtenstein},
            {"LT", Country.Lithuania},
            {"LU", Country.Luxembourg},
            {"MO", Country.Macau},
            {"MK", Country.Macedonia},
            {"MG", Country.Madagascar},
            {"MY", Country.Malaysia},
            {"MV", Country.Maldives},
            {"ML", Country.Mali},
            {"MT", Country.Malta},
            {"MQ", Country.Martinique},
            {"MU", Country.Mauritius},
            {"YT", Country.Mayotte},
            {"MX", Country.Mexico},
            {"MD", Country.Moldova},
            {"MC", Country.Monaco},
            {"MN", Country.Mongolia},
            {"ME", Country.Montenegro},
            {"MA", Country.Morocco},
            {"MZ", Country.Mozambique},
            {"MM", Country.Myanmar},
            {"NA", Country.Namibia},
            {"NP", Country.Nepal},
            {"NL", Country.Netherlands},
            {"NZ", Country.New_Zealand},
            {"NI", Country.Nicaragua},
            {"NG", Country.Nigeria},
            {"MP", Country.Northern_Mariana_Islands},
            {"NO", Country.Norway},
            {"OM", Country.Oman},
            {"PK", Country.Pakistan},
            {"PS", Country.Palestinian_Territory},
            {"PA", Country.Panama},
            {"PG", Country.Papua_New_Guinea},
            {"PY", Country.Paraguay},
            {"PE", Country.Peru},
            {"PH", Country.Philippines},
            {"PL", Country.Poland},
            {"PT", Country.Portugal},
            {"PR", Country.Puerto_Rico},
            {"QA", Country.Qatar},
            {"RE", Country.Reunion},
            {"RO", Country.Romania},
            {"RU", Country.Russian_Federation},
            {"RW", Country.Rwanda},
            {"LC", Country.Saint_Lucia},
            {"SA", Country.Saudi_Arabia},
            {"SN", Country.Senegal},
            {"RS", Country.Serbia},
            {"SC", Country.Seychelles},
            {"SG", Country.Singapore},
            {"SK", Country.Slovakia},
            {"SI", Country.Slovenia},
            {"ZA", Country.South_Africa},
            {"ES", Country.Spain},
            {"LK", Country.Sri_Lanka},
            {"KN", Country.Saint_Kitts_and_Nevis},
            {"PM", Country.Saint_Vincent_and_the_Grenadines},
            {"SD", Country.Sudan},
            {"SR", Country.Suriname},
            {"SE", Country.Sweden},
            {"CH", Country.Switzerland},
            {"TW", Country.Taiwan},
            {"TJ", Country.Tajikistan},
            {"TZ", Country.Tanzania},
            {"TH", Country.Thailand},
            {"TG", Country.Togo},
            {"TT", Country.Trinidad_and_Tobago},
            {"TN", Country.Tunisia},
            {"TR", Country.Turkey},
            {"TM", Country.Turkmenistan},
            {"TC", Country.Turks_and_Caicos_Islands},
            {"UG", Country.Uganda},
            {"UA", Country.Ukraine},
            {"GB", Country.United_Kingdom},
            {"VI", Country.Virgin_Islands},
            {"AE", Country.United_Arab_Emirates},
            {"UY", Country.Uruguay},
            {"UZ", Country.Uzbekistan},
            {"VE", Country.Venezuela},
            {"VN", Country.Viet_Nam},
            {"YE", Country.Yemen},
            {"ZM", Country.Zambia},
            {"ZW", Country.Zimbabwe}
        });

    public static IReadOnlyDictionary<Country, string> ResolveString { get; } = new Dictionary<Country, string>
    {
        {Country.Afghanistan, "Afghanistan"},
        {Country.Aland_Islands, "Aland Islands"},
        {Country.Albania, "Albania"},
        {Country.Algeria, "Algeria"},
        {Country.American_Samoa, "American Samoa"},
        {Country.Andorra, "Andorra"},
        {Country.Angola, "Angola"},
        {Country.Anguilla, "Anguilla"},
        {Country.Antigua_and_Barbuda, "Antigua and Barbuda"},
        {Country.Argentina, "Argentina"},
        {Country.Armenia, "Armenia"},
        {Country.Aruba, "Aruba"},
        {Country.Australia, "Australia"},
        {Country.Austria, "Austria"},
        {Country.Azerbaijan, "Azerbaijan"},
        {Country.Bahamas, "Bahamas"},
        {Country.Bahrain, "Bahrain"},
        {Country.Bangladesh, "Bangladesh"},
        {Country.Barbados, "Barbados"},
        {Country.Belarus, "Belarus"},
        {Country.Belgium, "Belgium"},
        {Country.Belize, "Belize"},
        {Country.Bhutan, "Bhutan"},
        {Country.Bolivia, "Bolivia"},
        {Country.Bosnia_and_Herzegovina, "Bosnia and Herzegovina"},
        {Country.Botswana, "Botswana"},
        {Country.Brazil, "Brazil"},
        {Country.Brunei_Darussalam, "Brunei Darussalam"},
        {Country.Bulgaria, "Bulgaria"},
        {Country.Burundi, "Burundi"},
        {Country.Cambodia, "Cambodia"},
        {Country.Cameroon, "Cameroon"},
        {Country.Canada, "Canada"},
        {Country.Cape_Verde, "Cape Verde"},
        {Country.Cayman_Islands, "Cayman Islands"},
        {Country.Chad, "Chad"},
        {Country.Chile, "Chile"},
        {Country.China, "China"},
        {Country.Colombia, "Colombia"},
        {Country.Congo, "Congo, the Democratic Republic of the"},
        {Country.Costa_Rica, "Costa Rica"},
        {Country.Cote_d_Ivoire, "Cote d'Ivoire"},
        {Country.Croatia, "Croatia"},
        {Country.Cyprus, "Cyprus"},
        {Country.Czech_Republic, "Czech Republic"},
        {Country.Denmark, "Denmark"},
        {Country.Dominica, "Dominica"},
        {Country.Dominican_Republic, "Dominican Republic"},
        {Country.Ecuador, "Ecuador"},
        {Country.Egypt, "Egypt"},
        {Country.El_Salvador, "El Salvador"},
        {Country.Estonia, "Estonia"},
        {Country.Eswatini, "Eswatini"},
        {Country.Ethiopia, "Ethiopia"},
        {Country.Faroe_Islands, "Faroe Islands"},
        {Country.Finland, "Finland"},
        {Country.France, "France"},
        {Country.French_Guiana, "French Guiana"},
        {Country.French_Polynesia, "French Polynesia"},
        {Country.Gabon, "Gabon"},
        {Country.Georgia, "Georgia"},
        {Country.Germany, "Germany"},
        {Country.Ghana, "Ghana"},
        {Country.Gibraltar, "Gibraltar"},
        {Country.Greece, "Greece"},
        {Country.Greenland, "Greenland"},
        {Country.Grenada, "Grenada"},
        {Country.Guadeloupe, "Guadeloupe"},
        {Country.Guam, "Guam"},
        {Country.Guatemala, "Guatemala"},
        {Country.Guernsey, "Guernsey"},
        {Country.Guyana, "Guyana"},
        {Country.Haiti, "Haiti"},
        {Country.Honduras, "Honduras"},
        {Country.Hong_Kong, "Hong Kong"},
        {Country.Hungary, "Hungary"},
        {Country.Iceland, "Iceland"},
        {Country.India, "India"},
        {Country.Indonesia, "Indonesia"},
        {Country.Iran, "Iran"},
        {Country.Iraq, "Iraq"},
        {Country.Ireland, "Ireland"},
        {Country.Isle_of_Man, "Isle of Man"},
        {Country.Israel, "Israel"},
        {Country.Italy, "Italy"},
        {Country.Jamaica, "Jamaica"},
        {Country.Japan, "Japan"},
        {Country.Jersey, "Jersey"},
        {Country.Jordan, "Jordan"},
        {Country.Kazakhstan, "Kazakhstan"},
        {Country.Kenya, "Kenya"},
        {Country.Korea, "Korea, Republic of"},
        {Country.Kuwait, "Kuwait"},
        {Country.Kyrgyzstan, "Kyrgyzstan"},
        {Country.Laos, "Lao People's Democratic Republic"},
        {Country.Latvia, "Latvia"},
        {Country.Lebanon, "Lebanon"},
        {Country.Libya, "Libya"},
        {Country.Liechtenstein, "Liechtenstein"},
        {Country.Lithuania, "Lithuania"},
        {Country.Luxembourg, "Luxembourg"},
        {Country.Macau, "Macau"},
        {Country.Macedonia, "Macedonia, the former Yugoslav Republic of"},
        {Country.Madagascar, "Madagascar"},
        {Country.Malaysia, "Malaysia"},
        {Country.Maldives, "Maldives"},
        {Country.Mali, "Mali"},
        {Country.Malta, "Malta"},
        {Country.Martinique, "Martinique"},
        {Country.Mauritius, "Mauritius"},
        {Country.Mayotte, "Mayotte"},
        {Country.Mexico, "Mexico"},
        {Country.Moldova, "Moldova, Republic of"},
        {Country.Monaco, "Monaco"},
        {Country.Mongolia, "Mongolia"},
        {Country.Montenegro, "Montenegro"},
        {Country.Morocco, "Morocco"},
        {Country.Mozambique, "Mozambique"},
        {Country.Myanmar, "Myanmar"},
        {Country.Namibia, "Namibia"},
        {Country.Nepal, "Nepal"},
        {Country.Netherlands, "Netherlands"},
        {Country.New_Zealand, "New Zealand"},
        {Country.Nicaragua, "Nicaragua"},
        {Country.Nigeria, "Nigeria"},
        {Country.Northern_Mariana_Islands, "Northern Mariana Islands"},
        {Country.Norway, "Norway"},
        {Country.Oman, "Oman"},
        {Country.Pakistan, "Pakistan"},
        {Country.Palestinian_Territory, "Palestinian Territory, Occupied"},
        {Country.Panama, "Panama"},
        {Country.Papua_New_Guinea, "Papua New Guinea"},
        {Country.Paraguay, "Paraguay"},
        {Country.Peru, "Peru"},
        {Country.Philippines, "Philippines"},
        {Country.Poland, "Poland"},
        {Country.Portugal, "Portugal"},
        {Country.Puerto_Rico, "Puerto Rico"},
        {Country.Qatar, "Qatar"},
        {Country.Reunion, "Reunion"},
        {Country.Romania, "Romania"},
        {Country.Russian_Federation, "Russian Federation"},
        {Country.Rwanda, "Rwanda"},
        {Country.Saint_Kitts_and_Nevis, "Saint Kitts and Nevis"},
        {Country.Saint_Lucia, "Saint Lucia"},
        {Country.Saint_Vincent_and_the_Grenadines, "Saint Vincent and the Grenadines"},
        {Country.Saudi_Arabia, "Saudi Arabia"},
        {Country.Senegal, "Senegal"},
        {Country.Serbia, "Serbia"},
        {Country.Seychelles, "Seychelles"},
        {Country.Singapore, "Singapore"},
        {Country.Slovakia, "Slovakia"},
        {Country.Slovenia, "Slovenia"},
        {Country.South_Africa, "South Africa"},
        {Country.Spain, "Spain"},
        {Country.Sri_Lanka, "Sri Lanka"},
        {Country.Sudan, "Sudan"},
        {Country.Suriname, "Suriname"},
        {Country.Sweden, "Sweden"},
        {Country.Switzerland, "Switzerland"},
        {Country.Taiwan, "Taiwan"},
        {Country.Tajikistan, "Tajikistan"},
        {Country.Tanzania, "Tanzania, United Republic of"},
        {Country.Thailand, "Thailand"},
        {Country.Togo, "Togo"},
        {Country.Trinidad_and_Tobago, "Trinidad and Tobago"},
        {Country.Tunisia, "Tunisia"},
        {Country.Turkey, "Turkey"},
        {Country.Turkmenistan, "Turkmenistan"},
        {Country.Turks_and_Caicos_Islands, "Turks and Caicos Islands"},
        {Country.Uganda, "Uganda"},
        {Country.Ukraine, "Ukraine"},
        {Country.United_Arab_Emirates, "United Arab Emirates"},
        {Country.United_Kingdom, "United Kingdom"},
        {Country.United_States, "United States"},
        {Country.Uruguay, "Uruguay"},
        {Country.Uzbekistan, "Uzbekistan"},
        {Country.Venezuela, "Venezuela"},
        {Country.Viet_Nam, "Viet Nam"},
        {Country.Virgin_Islands, "Virgin Islands, U.S."},
        {Country.Yemen, "Yemen"},
        {Country.Zambia, "Zambia"},
        {Country.Zimbabwe, "Zimbabwe"}
    };

    public static IReadOnlyDictionary<string, Country> ResolveCountry { get; } = new Dictionary<string, Country>()
    {
        {"Afghanistan", Country.Afghanistan},
        {"Aland Islands", Country.Aland_Islands},
        {"Albania", Country.Albania},
        {"Algeria", Country.Algeria},
        {"American Samoa", Country.American_Samoa},
        {"Andorra", Country.Andorra},
        {"Angola", Country.Angola},
        {"Anguilla", Country.Anguilla},
        {"Antigua and Barbuda", Country.Antigua_and_Barbuda},
        {"Argentina", Country.Argentina},
        {"Armenia", Country.Armenia},
        {"Aruba", Country.Aruba},
        {"Australia", Country.Australia},
        {"Austria", Country.Austria},
        {"Azerbaijan", Country.Azerbaijan},
        {"Bahamas", Country.Bahamas},
        {"Bahrain", Country.Bahrain},
        {"Bangladesh", Country.Bangladesh},
        {"Barbados", Country.Barbados},
        {"Belarus", Country.Belarus},
        {"Belgium", Country.Belgium},
        {"Belize", Country.Belize},
        {"Bhutan", Country.Bhutan},
        {"Bolivia", Country.Bolivia},
        {"Bosnia and Herzegovina", Country.Bosnia_and_Herzegovina},
        {"Botswana", Country.Botswana},
        {"Brazil", Country.Brazil},
        {"Brunei Darussalam", Country.Brunei_Darussalam},
        {"Bulgaria", Country.Bulgaria},
        {"Burundi", Country.Burundi},
        {"Cambodia", Country.Cambodia},
        {"Cameroon", Country.Cameroon},
        {"Canada", Country.Canada},
        {"Cape Verde", Country.Cape_Verde},
        {"Cayman Islands", Country.Cayman_Islands},
        {"Chad", Country.Chad},
        {"Chile", Country.Chile},
        {"China", Country.China},
        {"Colombia", Country.Colombia},
        {"Congo, the Democratic Republic of the", Country.Congo},
        {"Costa Rica", Country.Costa_Rica},
        {"Cote d'Ivoire", Country.Cote_d_Ivoire},
        {"Croatia", Country.Croatia},
        {"Cyprus", Country.Cyprus},
        {"Czech Republic", Country.Czech_Republic},
        {"Denmark", Country.Denmark},
        {"Dominica", Country.Dominica},
        {"Dominican Republic", Country.Dominican_Republic},
        {"Ecuador", Country.Ecuador},
        {"Egypt", Country.Egypt},
        {"El Salvador", Country.El_Salvador},
        {"Estonia", Country.Estonia},
        {"Eswatini", Country.Eswatini},
        {"Ethiopia", Country.Ethiopia},
        {"Faroe Islands", Country.Faroe_Islands},
        {"Finland", Country.Finland},
        {"France", Country.France},
        {"French Guiana", Country.French_Guiana},
        {"French Polynesia", Country.French_Polynesia},
        {"Gabon", Country.Gabon},
        {"Georgia", Country.Georgia},
        {"Germany", Country.Germany},
        {"Ghana", Country.Ghana},
        {"Gibraltar", Country.Gibraltar},
        {"Greece", Country.Greece},
        {"Greenland", Country.Greenland},
        {"Grenada", Country.Grenada},
        {"Guadeloupe", Country.Guadeloupe},
        {"Guam", Country.Guam},
        {"Guatemala", Country.Guatemala},
        {"Guernsey", Country.Guernsey},
        {"Guyana", Country.Guyana},
        {"Haiti", Country.Haiti},
        {"Honduras", Country.Honduras},
        {"Hong Kong", Country.Hong_Kong},
        {"Hungary", Country.Hungary},
        {"Iceland", Country.Iceland},
        {"India", Country.India},
        {"Indonesia", Country.Indonesia},
        {"Iran", Country.Iran},
        {"Iraq", Country.Iraq},
        {"Ireland", Country.Ireland},
        {"Isle of Man", Country.Isle_of_Man},
        {"Israel", Country.Israel},
        {"Italy", Country.Italy},
        {"Jamaica", Country.Jamaica},
        {"Japan", Country.Japan},
        {"Jersey", Country.Jersey},
        {"Jordan", Country.Jordan},
        {"Kazakhstan", Country.Kazakhstan},
        {"Kenya", Country.Kenya},
        {"Korea, Republic of", Country.Korea},
        {"Kuwait", Country.Kuwait},
        {"Kyrgyzstan", Country.Kyrgyzstan},
        {"Lao People's Democratic Republic", Country.Laos},
        {"Latvia", Country.Latvia},
        {"Lebanon", Country.Lebanon},
        {"Libya", Country.Libya},
        {"Liechtenstein", Country.Liechtenstein},
        {"Lithuania", Country.Lithuania},
        {"Luxembourg", Country.Luxembourg},
        {"Macau", Country.Macau},
        {"Macedonia, the former Yugoslav Republic of", Country.Macedonia},
        {"Madagascar", Country.Madagascar},
        {"Malaysia", Country.Malaysia},
        {"Maldives", Country.Maldives},
        {"Mali", Country.Mali},
        {"Malta", Country.Malta},
        {"Martinique", Country.Martinique},
        {"Mauritius", Country.Mauritius},
        {"Mayotte", Country.Mayotte},
        {"Mexico", Country.Mexico},
        {"Moldova, Republic of", Country.Moldova},
        {"Monaco", Country.Monaco},
        {"Mongolia", Country.Mongolia},
        {"Montenegro", Country.Montenegro},
        {"Morocco", Country.Morocco},
        {"Mozambique", Country.Mozambique},
        {"Myanmar", Country.Myanmar},
        {"Namibia", Country.Namibia},
        {"Nepal", Country.Nepal},
        {"Netherlands", Country.Netherlands},
        {"New Zealand", Country.New_Zealand},
        {"Nicaragua", Country.Nicaragua},
        {"Nigeria", Country.Nigeria},
        {"Northern Mariana Islands", Country.Northern_Mariana_Islands},
        {"Norway", Country.Norway},
        {"Oman", Country.Oman},
        {"Pakistan", Country.Pakistan},
        {"Palestinian Territory, Occupied", Country.Palestinian_Territory},
        {"Panama", Country.Panama},
        {"Papua New Guinea", Country.Papua_New_Guinea},
        {"Paraguay", Country.Paraguay},
        {"Peru", Country.Peru},
        {"Philippines", Country.Philippines},
        {"Poland", Country.Poland},
        {"Portugal", Country.Portugal},
        {"Puerto Rico", Country.Puerto_Rico},
        {"Qatar", Country.Qatar},
        {"Reunion", Country.Reunion},
        {"Romania", Country.Romania},
        {"Russian Federation", Country.Russian_Federation},
        {"Rwanda", Country.Rwanda},
        {"Saint Kitts and Nevis", Country.Saint_Kitts_and_Nevis},
        {"Saint Lucia", Country.Saint_Lucia},
        {"Saint Vincent and the Grenadines", Country.Saint_Vincent_and_the_Grenadines},
        {"Saudi Arabia", Country.Saudi_Arabia},
        {"Senegal", Country.Senegal},
        {"Serbia", Country.Serbia},
        {"Seychelles", Country.Seychelles},
        {"Singapore", Country.Singapore},
        {"Slovakia", Country.Slovakia},
        {"Slovenia", Country.Slovenia},
        {"South Africa", Country.South_Africa},
        {"Spain", Country.Spain},
        {"Sri Lanka", Country.Sri_Lanka},
        {"Sudan", Country.Sudan},
        {"Suriname", Country.Suriname},
        {"Sweden", Country.Sweden},
        {"Switzerland", Country.Switzerland},
        {"Taiwan", Country.Taiwan},
        {"Tajikistan", Country.Tajikistan},
        {"Tanzania, United Republic of", Country.Tanzania},
        {"Thailand", Country.Thailand},
        {"Togo", Country.Togo},
        {"Trinidad and Tobago", Country.Trinidad_and_Tobago},
        {"Tunisia", Country.Tunisia},
        {"Turkey", Country.Turkey},
        {"Turkmenistan", Country.Turkmenistan},
        {"Turks and Caicos Islands", Country.Turks_and_Caicos_Islands},
        {"Uganda", Country.Uganda},
        {"Ukraine", Country.Ukraine},
        {"United Arab Emirates", Country.United_Arab_Emirates},
        {"United Kingdom", Country.United_Kingdom},
        {"United States", Country.United_States},
        {"Uruguay", Country.Uruguay},
        {"Uzbekistan", Country.Uzbekistan},
        {"Venezuela", Country.Venezuela},
        {"Viet Nam", Country.Viet_Nam},
        {"Virgin Islands, U.S.", Country.Virgin_Islands},
        {"Yemen", Country.Yemen},
        {"Zambia", Country.Zambia},
        {"Zimbabwe", Country.Zimbabwe}
    };
}